// @playwright-project ui
import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { prisma } from "../lib/prisma";
import { createMeetingTemplate, deleteMeetingTemplate, updateMeetingTemplate } from "../lib/project-management/meetings/template-service";
import { copyMeetingTemplateContent } from "../lib/project-management/meetings/template-validation";
import { actor, createAccountPerson, createTask } from "./helpers/project-management-canvas-security-fixtures";
import { expectHealthyPage, loginAsTestUser } from "./helpers/functional-fixtures";

async function fixture() {
  const admin = await createAccountPerson(`模板界面超管 ${randomUUID()}`);
  const viewer = await createAccountPerson(`模板界面成员 ${randomUUID()}`);
  await prisma.systemRoleAssignment.create({ data: { accountId: admin.account.id, role: "SUPER_ADMINISTRATOR", team: "", techGroup: "" } });
  return { admin, viewer };
}

for (const viewport of [{ width: 1440, height: 1000 }, { width: 393, height: 851 }]) {
  test(`模板创建编辑、两个实例化入口与独立会议 ${viewport.width}`, async ({ page, context, baseURL }, testInfo) => {
    if (!baseURL) throw new Error("缺少隔离服务地址");
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    const { admin, viewer } = await fixture();
    const project = await prisma.project.create({ data: { name: `模板项目 ${randomUUID()}`, description: "", requesterAccountId: admin.account.id } });
    const task = await createTask({ ownerAccountId: admin.account.id, title: `模板任务 ${randomUUID()}`, team: "英雄", techGroup: "电控", members: [{ personId: admin.person.id, role: "OWNER" }] });
    const taskRecord = await prisma.task.findUniqueOrThrow({ where: { id: task.taskId } });
    await loginAsTestUser(context, baseURL, { openId: admin.openId, name: admin.person.displayName });
    await page.goto("/progress/meetings");
    await page.getByRole("link", { name: "创建模板", exact: true }).click();
    await expect(page.getByRole("heading", { name: "创建会议模板", exact: true })).toBeVisible();
    await expect(page.locator('input[type="datetime-local"]')).toHaveCount(0);
    await page.getByRole("button", { name: "创建会议模板", exact: true }).click();
    await expect(page.getByLabel("模板名称", { exact: true })).toBeFocused();
    const name = `每周组会 ${randomUUID()}`;
    await page.getByLabel("模板名称", { exact: true }).fill(name);
    await page.getByLabel("模板说明", { exact: true }).fill("长模板说明".repeat(60));
    await page.getByLabel("会议主题", { exact: true }).fill("项目进展与下周计划");
    await page.getByRole("combobox", { name: "会议参与人", exact: true }).fill(viewer.person.displayName);
    await page.getByRole("option").filter({ hasText: viewer.person.displayName }).click();
    await page.getByRole("combobox", { name: "展示项目", exact: true }).fill(project.name);
    await page.getByRole("option").filter({ hasText: project.name }).click();
    await page.getByRole("combobox", { name: "展示任务", exact: true }).fill(taskRecord.title);
    await page.getByRole("option").filter({ hasText: taskRecord.title }).click();
    await page.getByLabel("会议纪要", { exact: true }).fill("# 会议议程\n## 讨论\n## 下周计划");
    await expectHealthyPage(page);
    await page.getByRole("button", { name: "创建会议模板", exact: true }).click();
    await expect(page).toHaveURL(/\/progress\/meetings\?templateSaved=1$/);
    const card = page.getByRole("article", { name, exact: true });
    await expect(card).toBeVisible();
    await expectHealthyPage(page);
    await card.locator("summary").filter({ hasText: "展开说明" }).click();
    await expect(card.locator("details[open]")).toContainText("长模板说明".repeat(60));
    await expectHealthyPage(page);
    await card.locator("summary").filter({ hasText: "展开说明" }).click();
    await page.screenshot({ path: testInfo.outputPath("meeting-templates.png"), fullPage: true });
    const template = await prisma.meetingTemplate.findFirstOrThrow({ where: { name } });
    await card.getByRole("link", { name: "编辑", exact: true }).click();
    await page.getByLabel("会议主题", { exact: true }).fill("模板修改后的主题");
    await page.getByRole("button", { name: "保存模板修改", exact: true }).click();
    await expect(page).toHaveURL(/templateSaved=1$/);
    await card.getByRole("link", { name: "使用模板", exact: true }).click();
    await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("模板修改后的主题");
    await expect(page.getByLabel("会议纪要", { exact: true })).toHaveValue("# 会议议程\n## 讨论\n## 下周计划");
    await page.screenshot({ path: testInfo.outputPath("meeting-from-template.png"), fullPage: true });
    await expect(page.getByText(viewer.person.displayName, { exact: true })).toBeVisible();
    const start = page.getByLabel("工作开始时间（北京时间）", { exact: true });
    const end = page.getByLabel("工作结束时间（北京时间）", { exact: true });
    expect(Date.parse(await end.inputValue()) - Date.parse(await start.inputValue())).toBe(7 * 86_400_000);
    await start.fill("2026-09-01T09:00");
    await end.fill("2026-09-08T10:00");
    await page.getByRole("button", { name: "预览工作时间线", exact: true }).click();
    await expect(page.getByTestId("meeting-timeline")).toBeVisible();
    const empty = await createMeetingTemplate(actor(admin), { requestId: randomUUID(), name: `空内容模板 ${randomUUID()}`, topic: "空值替换", personIds: [viewer.person.id], minutes: "", timelineDisplay: { projectIds: [], taskIds: [] } });
    await page.getByRole("button", { name: "更换模板", exact: true }).click();
    page.once("dialog", (dialog) => dialog.dismiss());
    await page.getByRole("dialog", { name: "选择会议模板" }).getByRole("article", { name: empty.name }).getByRole("button", { name: "使用模板" }).click();
    await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("模板修改后的主题");
    await page.getByRole("button", { name: "更换模板", exact: true }).click();
    page.once("dialog", (dialog) => dialog.accept());
    await page.getByRole("dialog", { name: "选择会议模板" }).getByRole("article", { name: empty.name }).getByRole("button", { name: "使用模板" }).click();
    await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("空值替换");
    await expect(page.getByLabel("会议纪要", { exact: true })).toHaveValue("");
    await expect(page.getByTestId("meeting-timeline")).toHaveCount(0);
    await expect(start).toHaveValue("2026-09-01T09:00");
    await expect(end).toHaveValue("2026-09-08T10:00");
    await page.getByRole("button", { name: "关闭模板提示", exact: true }).click();
    await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("空值替换");
    await deleteMeetingTemplate(actor(admin), { templateId: empty.id, expectedVersion: empty.version });
    await page.getByLabel("会议主题", { exact: true }).fill(`独立会议 ${name}`);
    await page.getByLabel("会议纪要", { exact: true }).fill("会议自定义纪要");
    await expectHealthyPage(page);
    await page.getByRole("button", { name: "创建会议记录", exact: true }).click();
    await expect(page).toHaveURL(/\/progress\/meetings\/[a-f0-9-]+\?saved=1$/);
    const meeting = await prisma.meetingRecord.findFirstOrThrow({ where: { topic: `独立会议 ${name}` }, include: { participants: true } });
    expect(meeting.minutes).toBe("会议自定义纪要");
    expect(meeting.timelineDisplay).toEqual({ projectIds: [], taskIds: [] });
    expect(meeting.participants.map((person) => person.personId)).toEqual([viewer.person.id]);
    expect(meeting.rangeStart.toISOString()).toBe("2026-09-01T01:00:00.000Z");
    expect((await prisma.meetingTemplate.findUniqueOrThrow({ where: { id: template.id } })).minutes).toBe("# 会议议程\n## 讨论\n## 下周计划");
    await page.goto("/progress/meetings");
    page.once("dialog", (dialog) => dialog.accept());
    await card.getByRole("button", { name: "删除", exact: true }).click();
    await expect(card).toHaveCount(0);
    expect((await prisma.meetingTemplate.findUniqueOrThrow({ where: { id: template.id } })).deletedAt).not.toBeNull();
    expect(await prisma.meetingRecord.count({ where: { id: meeting.id } })).toBe(1);
    await expectHealthyPage(page);
    expect(errors).toEqual([]);
  });
}

test("模板不可用、加载失败、并发冲突保留草稿且普通用户无模板权限", async ({ page, context, baseURL }) => {
  if (!baseURL) throw new Error("缺少隔离服务地址");
  const { admin, viewer } = await fixture();
  const template = await createMeetingTemplate(actor(admin), { requestId: randomUUID(), name: `冲突模板 ${randomUUID()}`, topic: "主题", personIds: [viewer.person.id] });
  await loginAsTestUser(context, baseURL, { openId: admin.openId, name: admin.person.displayName });
  await page.goto(`/progress/meetings/templates/${template.id}/edit`);
  await page.getByLabel("会议主题", { exact: true }).fill("保留我的修改");
  await updateMeetingTemplate(actor(admin), { ...copyMeetingTemplateContent(template), name: template.name, description: "另一窗口修改", templateId: template.id, expectedVersion: 0 });
  await page.getByRole("button", { name: "保存模板修改", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "其他管理员修改" })).toBeVisible();
  await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("保留我的修改");
  page.once("dialog", (dialog) => dialog.accept());
  await page.goto(`/progress/meetings/new?templateId=${randomUUID()}`);
  await expect(page.getByRole("alert").filter({ hasText: "模板未填充" })).toBeVisible();
  await page.getByLabel("会议主题", { exact: true }).fill("网络故障不清空");
  await page.route("**/progress/meetings/new**", async (route) => {
    if (route.request().method() === "POST") await route.abort();
    else await route.continue();
  });
  await page.getByRole("button", { name: "使用模板", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toContainText("模板加载失败");
  await page.unroute("**/progress/meetings/new**");
  await page.getByRole("button", { name: "重新加载模板" }).click();
  await expect(page.getByRole("dialog").getByRole("article", { name: template.name })).toBeVisible();
  await deleteMeetingTemplate(actor(admin), { templateId: template.id, expectedVersion: 1 });
  await page.getByRole("dialog").getByRole("article", { name: template.name }).getByRole("button", { name: "使用模板" }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toContainText("不存在或无权查看");
  await page.keyboard.press("Escape");
  await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("网络故障不清空");
  await expectHealthyPage(page);
  page.once("dialog", (dialog) => dialog.accept());
  await page.goto("/progress/meetings");
  await loginAsTestUser(context, baseURL, { openId: viewer.openId, name: viewer.person.displayName });
  await page.goto("/progress/meetings");
  await expect(page.getByRole("region", { name: "会议模板", exact: true })).toHaveCount(0);
  for (const path of ["/progress/meetings/templates/new", `/progress/meetings/templates/${template.id}/edit`]) {
    await page.goto(path);
    await expect(page.getByRole("alert").filter({ hasText: "只有全局超级管理员" })).toBeVisible();
    await expect(page.getByLabel("模板名称", { exact: true })).toHaveCount(0);
    await expectHealthyPage(page);
  }
});

test("模板预填保留不可用引用并显示可修正的字段错误", async ({ page, context, baseURL }) => {
  if (!baseURL) throw new Error("缺少隔离服务地址");
  const { admin, viewer } = await fixture();
  const project = await prisma.project.create({ data: { name: `不可用模板项目 ${randomUUID()}`, description: "", requesterAccountId: admin.account.id } });
  const template = await createMeetingTemplate(actor(admin), { requestId: randomUUID(), name: `不可用引用 ${randomUUID()}`, topic: "保留非时间内容", personIds: [viewer.person.id], minutes: "修正对象之前不要清空", timelineDisplay: { projectIds: [project.id], taskIds: [] } });
  await prisma.person.update({ where: { id: viewer.person.id }, data: { status: "INACTIVE" } });
  await prisma.project.update({ where: { id: project.id }, data: { deletedAt: new Date() } });
  await loginAsTestUser(context, baseURL, { openId: admin.openId, name: admin.person.displayName });
  await page.goto(`/progress/meetings/new?templateId=${template.id}`);
  await expect(page.getByRole("combobox", { name: "会议参与人", exact: true })).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByRole("combobox", { name: "展示项目", exact: true })).toHaveAttribute("aria-invalid", "true");
  await expect(page.getByText("参与人不存在或已停用，请重新选择", { exact: true })).toBeVisible();
  await expect(page.getByText("所选项目不存在或已不可用，请重新选择", { exact: true })).toBeVisible();
  await expect(page.getByLabel("会议纪要", { exact: true })).toHaveValue(template.minutes);
  await expect(page.getByText(project.name, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "创建会议记录", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "参与人不存在或已停用" }).first()).toBeVisible();
  await expect(page.getByRole("combobox", { name: "会议参与人", exact: true })).toBeFocused();
  expect(await prisma.meetingRecord.count({ where: { topic: template.topic } })).toBe(0);
  await expectHealthyPage(page);
});

test("模板分页独立于会议筛选并支持键盘选择", async ({ page, context, baseURL }) => {
  if (!baseURL) throw new Error("缺少隔离服务地址");
  const { admin, viewer } = await fixture();
  const prefix = `分页 ${randomUUID()}`;
  for (let index = 0; index < 12; index++) await createMeetingTemplate(actor(admin), { requestId: randomUUID(), name: `${prefix} ${index}`, topic: `分页主题 ${index}`, personIds: [viewer.person.id] });
  await loginAsTestUser(context, baseURL, { openId: admin.openId, name: admin.person.displayName });
  await page.goto(`/progress/meetings?q=${encodeURIComponent(randomUUID())}`);
  await expect(page.getByText("没有符合条件的会议", { exact: true })).toBeVisible();
  await expect(page.getByRole("article", { name: `${prefix} 11`, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "下一页模板" }).click();
  await expect(page.getByRole("article", { name: `${prefix} 0`, exact: true })).toBeVisible();
  await expect(page).toHaveURL(/\?q=/);
  await page.getByRole("button", { name: "上一页模板" }).click();
  await expect(page.getByRole("article", { name: `${prefix} 11`, exact: true })).toBeVisible();
  await page.goto("/progress/meetings/new");
  const picker = page.getByRole("button", { name: "使用模板", exact: true });
  await picker.focus();
  await page.keyboard.press("Enter");
  const select = page.getByRole("dialog").getByRole("article", { name: `${prefix} 11`, exact: true }).getByRole("button", { name: "使用模板" });
  await select.focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByLabel("会议主题", { exact: true })).toHaveValue("分页主题 11");
  await expectHealthyPage(page);
});
