// @playwright-project ui
import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { prisma } from "../lib/prisma";
import { createUiFixture } from "./helpers/project-management-ui-fixtures";
import { expectHealthyPage, expectNoHorizontalOverflow, loginAsTestUser } from "./helpers/functional-fixtures";

for (const width of [1440, 393, 360]) {
  test(`投入草稿跨行拖动预览跟随指针并正确保存 ${width}`, async ({ page, context, baseURL }, testInfo) => {
    test.setTimeout(90_000);
    await page.setViewportSize({ width, height: width === 1440 ? 1000 : 851 });
    const fixture = await createUiFixture();
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await loginAsTestUser(context, baseURL, { openId: fixture.admin.openId, name: fixture.admin.person.displayName });
    await page.goto(`/progress/resources?all=0&people=${fixture.member.person.id},${fixture.owner.person.id},${fixture.inactiveHistory.person.id}&scale=week&center=2026-08-10T09%3A00%3A00.000Z`);
    await page.getByRole("button", { name: "新增投入", exact: true }).click();
    const form = page.getByRole("form", { name: "投入快速创建" });
    const personInput = form.locator('input[name="personId"]');
    const draft = page.getByTestId("time-canvas-creation-range");
    const preview = page.getByTestId("time-canvas-creation-drag-preview");
    const initialPerson = await personInput.inputValue();
    const narrowTarget = initialPerson === fixture.member.person.id ? fixture.owner.person : fixture.member.person;
    await page.getByTestId("time-canvas-scroll").scrollIntoViewIfNeeded();
    const narrowSourceBox = await draft.boundingBox();
    const narrowTargetBox = await page.locator(`[data-canvas-row="person:${narrowTarget.id}"]`).boundingBox();
    if (!narrowSourceBox || !narrowTargetBox) throw new Error("缺少默认窄草稿坐标");
    expect(narrowSourceBox.width).toBeLessThanOrEqual(12);
    const initialStart = await form.getByLabel("开始", { exact: true }).inputValue();
    const initialEnd = await form.getByLabel("结束", { exact: true }).inputValue();
    await page.mouse.move(narrowSourceBox.x + narrowSourceBox.width / 2, narrowSourceBox.y + narrowSourceBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(narrowSourceBox.x + narrowSourceBox.width / 2, narrowTargetBox.y + narrowTargetBox.height / 2, { steps: 8 });
    await expect(preview).toBeVisible();
    await page.mouse.up();
    await expect(personInput).toHaveValue(narrowTarget.id);
    await expect(form.getByLabel("开始", { exact: true })).toHaveValue(initialStart);
    await expect(form.getByLabel("结束", { exact: true })).toHaveValue(initialEnd);
    await form.getByLabel("开始", { exact: true }).fill("2026-08-09T08:00");
    await form.getByLabel("结束", { exact: true }).fill("2026-08-12T08:00");
    const content = `跨行预览归属 ${randomUUID()}`;
    await form.getByLabel("内容", { exact: true }).fill(content);
    const originalPerson = await personInput.inputValue();
    const targetPerson = originalPerson === fixture.member.person.id ? fixture.owner.person : fixture.member.person;
    const sourceHeader = page.getByTestId(`time-canvas-row-header-person:${originalPerson}`);
    const target = page.locator(`[data-canvas-row="person:${targetPerson.id}"]`);
    const invalidTarget = page.locator(`[data-canvas-row="person:${fixture.inactiveHistory.person.id}"]`);
    await page.getByTestId("time-canvas-scroll").scrollIntoViewIfNeeded();
    const source = await draft.boundingBox();
    const destination = await target.boundingBox();
    const invalid = await invalidTarget.boundingBox();
    const header = await sourceHeader.boundingBox();
    const viewport = await page.getByTestId("time-canvas-scroll").boundingBox();
    if (!source || !destination || !invalid || !header || !viewport) throw new Error("缺少跨行拖动坐标");
    const x = Math.max(header.x + header.width + 16, Math.min(source.x + source.width / 2, viewport.x + viewport.width - 24));
    const startY = source.y + source.height / 2;
    const targetY = destination.y + destination.height / 2;
    await page.mouse.move(x, startY);
    await page.mouse.down();
    await page.mouse.move(x + 8, targetY, { steps: 8 });
    await expect(target).toHaveAttribute("data-creation-drop-state", "valid");
    await expect(preview).toBeVisible();
    await expect.poll(async () => {
      const bounds = await preview.boundingBox();
      return bounds ? Math.abs(bounds.y + bounds.height / 2 - targetY) : Infinity;
    }).toBeLessThan(2);
    await expect(draft).toHaveCSS("opacity", "0");
    await expect(personInput).toHaveValue(originalPerson);
    await expect(preview).toHaveCSS("pointer-events", "none");
    await page.screenshot({ path: testInfo.outputPath(`draft-cross-row-${width}.png`), animations: "disabled" });

    // An invalid row must not commit the preview's time or person changes.
    const startBefore = await form.getByLabel("开始", { exact: true }).inputValue();
    await page.mouse.move(x, invalid.y + invalid.height / 2, { steps: 8 });
    await expect(invalidTarget).toHaveAttribute("data-creation-drop-state", "invalid");
    await page.mouse.up();
    await expect(preview).toHaveCount(0);
    await expect(draft).toHaveCSS("opacity", "1");
    await expect(personInput).toHaveValue(originalPerson);
    await expect(form.getByLabel("开始", { exact: true })).toHaveValue(startBefore);
    await expect(page.locator("[data-creation-drop-state]")).toHaveCount(0);

    const cancelSource = await draft.boundingBox();
    const cancelDestination = await target.boundingBox();
    if (!cancelSource || !cancelDestination) throw new Error("缺少取消拖动坐标");
    await page.mouse.move(x, cancelSource.y + cancelSource.height / 2);
    await page.mouse.down();
    await page.mouse.move(x, cancelDestination.y + cancelDestination.height / 2, { steps: 8 });
    await expect(preview).toBeVisible();
    await draft.dispatchEvent("pointercancel", { pointerId: 1, pointerType: "mouse" });
    await page.mouse.up();
    await expect(preview).toHaveCount(0);
    await expect(personInput).toHaveValue(originalPerson);
    await expect(page.locator("[data-creation-drop-state]")).toHaveCount(0);

    const restored = await draft.boundingBox();
    const destinationNow = await target.boundingBox();
    if (!restored || !destinationNow) throw new Error("缺少恢复后的草稿坐标");
    await page.mouse.move(x, restored.y + restored.height / 2);
    await page.mouse.down();
    await page.mouse.move(x, destinationNow.y + destinationNow.height / 2, { steps: 8 });
    await expect(preview).toBeVisible();
    await page.mouse.up();
    await expect(preview).toHaveCount(0);
    await expect(personInput).toHaveValue(targetPerson.id);
    await expect(target.getByTestId("time-canvas-creation-range")).toBeVisible();
    await expect(page.locator("[data-creation-drop-state]")).toHaveCount(0);
    const endBeforeResize = await form.getByLabel("结束", { exact: true }).inputValue();
    const resizeHandle = draft.locator('[data-create-resize-handle="end"]');
    const handle = await resizeHandle.boundingBox();
    if (!handle) throw new Error("缺少草稿边缘坐标");
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await page.mouse.down();
    await page.mouse.move(handle.x + handle.width / 2 - 16, handle.y + handle.height / 2, { steps: 4 });
    await expect(preview).toHaveCount(0);
    await expect(draft).toHaveCSS("opacity", "1");
    await page.mouse.up();
    await expect(form.getByLabel("结束", { exact: true })).not.toHaveValue(endBeforeResize);
    await expect(personInput).toHaveValue(targetPerson.id);
    await form.getByRole("button", { name: "创建", exact: true }).click();
    await expect(form).not.toBeVisible();
    const saved = await prisma.workSegment.findFirstOrThrow({ where: { content } });
    expect(saved.personId).toBe(targetPerson.id);
    await expectHealthyPage(page);
    await expectNoHorizontalOverflow(page);
    expect(errors).toEqual([]);
  });
}
