#!/bin/sh
set -eu

SERVER_SERVICE_NAME="pnx-management-server.service"
CRON_SERVICE_NAME="pnx-management-cron.service"

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
ENV_SOURCE=${ENV_SOURCE:-"$PROJECT_DIR/.env"}
SYSTEMD_DIR=${SYSTEMD_DIR:-/etc/systemd/system}
ENV_DIR=${ENV_DIR:-/etc/pnx-management}
ENV_FILE=${ENV_FILE:-"$ENV_DIR/pnx-management.env"}

if [ -f "$ENV_SOURCE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_SOURCE"
  set +a
fi

SERVICE_USER=${SERVICE_USER:-${SUDO_USER:-$(id -un)}}
SERVICE_GROUP=${SERVICE_GROUP:-$(id -gn "$SERVICE_USER" 2>/dev/null || id -gn)}
PORT=${APP_PORT:-${PORT:-3000}}

find_command() {
  command -v "$1" 2>/dev/null || true
}

NODE_BIN=${NODE_BIN:-$(find_command node)}
NPM_BIN=${NPM_BIN:-$(find_command npm)}

if [ -z "$NODE_BIN" ] || [ -z "$NPM_BIN" ]; then
  echo "Cannot find node/npm in PATH. Load your Node environment first, then rerun service/install.sh." >&2
  exit 1
fi

NODE_BIN_DIR=$(dirname "$NODE_BIN")

run_root() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
    return
  fi

  if sudo -n true >/dev/null 2>&1; then
    sudo "$@"
    return
  fi

  if [ -n "${SUDO_PASSWORD:-}" ]; then
    printf '%s\n' "$SUDO_PASSWORD" | sudo -S -p "" "$@"
    return
  fi

  sudo "$@"
}

sed_escape() {
  printf '%s' "$1" | sed -e 's/[\/&]/\\&/g'
}

render_template() {
  template=$1
  output=$2
  sed \
    -e "s/__SERVICE_USER__/$(sed_escape "$SERVICE_USER")/g" \
    -e "s/__SERVICE_GROUP__/$(sed_escape "$SERVICE_GROUP")/g" \
    -e "s/__PROJECT_DIR__/$(sed_escape "$PROJECT_DIR")/g" \
    -e "s/__ENV_FILE__/$(sed_escape "$ENV_FILE")/g" \
    -e "s/__PORT__/$(sed_escape "$PORT")/g" \
    -e "s/__NODE_BIN_DIR__/$(sed_escape "$NODE_BIN_DIR")/g" \
    -e "s/__NPM_BIN__/$(sed_escape "$NPM_BIN")/g" \
    "$template" > "$output"
}

quote_env_value() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

normalize_database_url() {
  value=${DATABASE_URL:-file:./dev.db}
  case "$value" in
    file:/*)
      printf '%s' "$value"
      ;;
    file:./*)
      printf 'file:%s/%s' "$PROJECT_DIR" "$(printf '%s' "${value#file:./}")"
      ;;
    file:*)
      printf 'file:%s/%s' "$PROJECT_DIR" "$(printf '%s' "${value#file:}")"
      ;;
    *)
      printf '%s' "$value"
      ;;
  esac
}

write_runtime_env() {
  output=$1
  database_url=$(normalize_database_url)

  {
    printf '# Generated by %s. Do not put host-only secrets here.\n' "$0"
    printf 'DATABASE_URL="%s"\n' "$(quote_env_value "$database_url")"
    printf 'PORT="%s"\n' "$(quote_env_value "$PORT")"
    printf 'HOSTNAME="0.0.0.0"\n'

    if [ -f "$ENV_SOURCE" ]; then
      while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
          ''|\#*)
            printf '%s\n' "$line"
            ;;
          DATABASE_URL=*|PORT=*|HOSTNAME=*|APP_PORT=*|SUDO_PASSWORD=*|RUN_DB_SEED=*|SKIP_DB_PUSH=*)
            ;;
          *)
            printf '%s\n' "$line"
            ;;
        esac
      done < "$ENV_SOURCE"
    fi
  } > "$output"
}

tmp_dir=$(mktemp -d)
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT INT TERM

server_unit="$tmp_dir/$SERVER_SERVICE_NAME"
cron_unit="$tmp_dir/$CRON_SERVICE_NAME"
runtime_env="$tmp_dir/pnx-management.env"

render_template "$SCRIPT_DIR/$SERVER_SERVICE_NAME" "$server_unit"
render_template "$SCRIPT_DIR/$CRON_SERVICE_NAME" "$cron_unit"
write_runtime_env "$runtime_env"

if [ "${DRY_RUN:-false}" = "true" ]; then
  dry_run_dir=${DRY_RUN_DIR:-/tmp/pnx-management-service-dry-run}
  mkdir -p "$dry_run_dir/systemd" "$dry_run_dir/env"
  install -m 0644 "$server_unit" "$dry_run_dir/systemd/$SERVER_SERVICE_NAME"
  install -m 0644 "$cron_unit" "$dry_run_dir/systemd/$CRON_SERVICE_NAME"
  install -m 0600 "$runtime_env" "$dry_run_dir/env/pnx-management.env"
  echo "Dry run rendered files to $dry_run_dir"
  echo "No systemd service was installed or started."
  exit 0
fi

run_root install -d -m 0755 "$ENV_DIR"
run_root install -m 0600 "$runtime_env" "$ENV_FILE"
run_root install -m 0644 "$server_unit" "$SYSTEMD_DIR/$SERVER_SERVICE_NAME"
run_root install -m 0644 "$cron_unit" "$SYSTEMD_DIR/$CRON_SERVICE_NAME"
run_root systemctl daemon-reload
run_root systemctl enable --now "$SERVER_SERVICE_NAME"
run_root systemctl enable --now "$CRON_SERVICE_NAME"

echo "Installed and enabled:"
echo "  $SERVER_SERVICE_NAME"
echo "  $CRON_SERVICE_NAME"
echo
echo "Useful commands:"
echo "  systemctl status $SERVER_SERVICE_NAME --no-pager"
echo "  systemctl status $CRON_SERVICE_NAME --no-pager"
echo "  journalctl -u $SERVER_SERVICE_NAME -f"
echo "  journalctl -u $CRON_SERVICE_NAME -f"
